language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep8
    - python: 2.7
      env: TOX_ENV=pylint
    - python: 2.7
      env: TOX_ENV=py27

    - python: 3.4
      env: TOX_ENV=pep8
    - python: 3.4
      env: TOX_ENV=pylint
    - python: 3.4
      env: TOX_ENV=py34

    - python: 3.5
      env: TOX_ENV=pep8
    - python: 3.5
      env: TOX_ENV=pylint
    - python: 3.5
      env: TOX_ENV=py35

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e "${TOX_ENV}"

after_success:
  - '[[ "${TOX_ENV}" = "py27" ]] && coveralls'
